/**
 * NAUI Course Templates
 * Source: NAUI Standards and Policies Manual, 2026 Edition
 *
 * Skills are separated into three environments:
 *   knowledgeSkills  — academic/knowledge objectives
 *   confinedSkills   — confined water (pool/controlled) skills
 *   openWaterSkills  — open water dive skills
 *
 * Skills appearing in BOTH confined and open water require independent sign-off
 * in each environment (introduced in CW, then demonstrated in OW).
 * All minimums per the NAUI 2026 S&P.
 */

export type CourseLevel = 'beginner' | 'intermediate' | 'advanced' | 'professional';

export interface CourseTemplate {
  id: string;
  name: string;
  level: CourseLevel;
  description: string;
  knowledgeSkills: string[];
  confinedSkills: string[];
  openWaterSkills: string[];
  minKnowledgeHours?: number;      // minimum academic/knowledge hours per NAUI 2026 S&P
  minConfinedWaterHours?: number;  // minimum confined water hours per NAUI 2026 S&P
  trainingDiveCount?: number;      // minimum required open water dives per NAUI 2026 S&P
}

export const COURSE_TEMPLATES: CourseTemplate[] = [
  // ─────────────────────────────────────────────
  // INTRODUCTORY / ENTRY-LEVEL COURSES
  // ─────────────────────────────────────────────
  {
    id: 'tpl_intro_scuba',
    name: 'Introduction to Scuba (ISO 11121)',
    level: 'beginner',
    description: 'Non-certification introductory program. Participants may conduct an optional open water dive to 12 m (40 ft) in closely controlled conditions. A participation certificate is issued; no certification card. Min. 1 hr academic, 1 hr confined water (1 confined dive), 1 optional OW dive (age 10+).',
    minKnowledgeHours: 1,
    minConfinedWaterHours: 1,
    knowledgeSkills: [
      'Explain each piece of equipment and its function',
      'Explain diving physics basics: light, sound, gas laws, direct/indirect pressure effects, thermal concerns',
      'Explain proper ear and sinus equalization technique',
      'Explain the importance of proper continuous breathing during scuba',
      'Explain effects of pressure on air consumption',
      'Explain buoyancy control: weights, breathing, and BC use',
      'Explain physiological hazards and fitness-to-dive considerations',
      'Demonstrate basic underwater hand signals',
      'Explain local aquatic life hazards and environmental concerns',
      'List safety rules for diving under professional supervision',
      'Explain emergency procedures appropriate to the setting',
    ],
    confinedSkills: [
      'Don, adjust, and fit all equipment',
      'Pre-dive buddy check (BWRAF or equivalent)',
      'Propel self efficiently at the surface and underwater',
      'Equalize pressure in body spaces during descent',
      'Breathe comfortably from scuba underwater',
      'Breathe from scuba without a face mask',
      'Regain primary regulator from behind shoulder, replace, and clear',
      'Remove, replace, and clear a mask',
      'BC oral and power inflation and deflation underwater',
      'Establish neutral buoyancy and hover without support',
      'Share air as both donor and receiver (alternate air source)',
      'Monitor instruments and communicate air supply to buddy/instructor',
      'Surface normally breathing from scuba',
      'Establish surface flotation using BC (power and oral)',
    ],
    openWaterSkills: [
      'Comfortable entries and exits as appropriate for the environment',
      'Dive effectively with a buddy in a directly supervised group',
      'Identify significant plant and animal life encountered',
    ],
  },
  {
    id: 'tpl_scuba_diver',
    name: 'Scuba Diver (Supervised, ISO 24801-1)',
    level: 'beginner',
    description: 'Entry certification for supervised diving to 12 m (40 ft). Certified Scuba Divers may only dive under direct supervision of an active NAUI Instructor or Divemaster. Stepping stone to Open Water Scuba Diver. Min. 10 hrs academic, 5 hrs water, 2 OW dives.',
    minKnowledgeHours: 10,
    trainingDiveCount: 2,
    knowledgeSkills: [
      'Explain all equipment and the function each performs',
      'Understand basics of diving physics: light, sound, gas laws, direct/indirect pressure effects, thermal concerns',
      'Explain proper equalization technique',
      'Explain the importance of proper scuba breathing',
      'Explain effects of pressure on air consumption',
      'Explain buoyancy control: weights, breathing, and BC use',
      'Explain physiological hazards that may impact fitness to dive',
      'Demonstrate underwater hand signals and communication',
      'Explain local aquatic life and environmental hazards',
      'List safety rules for diving under professional supervision in open water',
      'Explain emergency procedures',
    ],
    confinedSkills: [
      'Assemble, don, and adjust all equipment',
      'Perform pre-dive buddy check',
      'Use effective communication and hand signals',
      'Perform surface buoyancy/weighting check and adjust',
      'Equalize diver air spaces during descent',
      'Breathe comfortably from scuba underwater',
      'Regulator/snorkel exchange while swimming at the surface',
      'Regulator clearing and recovery (from behind shoulder)',
      'Clear a fully flooded mask',
      'Remove, replace, and clear a mask',
      'Breathe from scuba underwater without a mask',
      'Monitor instruments and communicate air amount to buddy/instructor',
      'Demonstrate environmentally appropriate buoyancy control',
      'Demonstrate environmentally appropriate propulsion technique',
      'Remove and replace ballast system',
      'Problem solve underwater while maintaining awareness',
      'Surface normally breathing from scuba',
      'Establish surface buoyancy using BC (power and oral inflation)',
      'Emergency swimming ascent (ESA) practice in confined water',
      'Share air as both donor and receiver via alternate air source in confined water',
    ],
    openWaterSkills: [
      'Comfortable entries and exits appropriate for the environment',
      'Effectively dive with a buddy in a directly supervised group',
      'Identify significant plant and animal life encountered',
      'Disassemble and care for equipment after diving',
      'Perform relaxed emergency swimming ascent (ESA) from ≥ 4.6 m (15 ft) with oral BC inflation on surfacing',
      'Share air as both donor and receiver from alternate air source during ascents from ≥ 4.6 m (15 ft)',
    ],
  },
  {
    id: 'tpl_ow',
    name: 'Open Water Scuba Diver (ISO 24801-2)',
    level: 'beginner',
    description: 'NAUI entry-level autonomous diver certification. Graduates may dive without direct supervision to 18 m (60 ft) in conditions approximating training. Min. 14 hrs academic, 17 hrs total practical (≥10 in-water), 4 OW dives. Max depth 18 m (60 ft).',
    minKnowledgeHours: 14,
    trainingDiveCount: 4,
    knowledgeSkills: [
      'Physics: gases, pressure, volume, temperature, density, buoyancy, vision, acoustics',
      'Physiology: nitrogen narcosis, shallow water blackout, barotrauma, decompression illness (DCS & AGE) — causes, prevention, symptoms, first aid',
      'Equipment: purpose, types, use, and care of all recreational scuba gear; instrument use; dive computers vs. tables',
      'Diving safety: emergency procedures, rescue/first aid, underwater comms, basic navigation, dive planning, emergency O2 first aid',
      'Diving environment: physical and biological aspects, hazard recognition before entry, conservation principles, regulations',
      'Diving activities: dive clubs, boats, stores, locations, publications; importance of logbook use',
      'Continuing education: personal limitations as a new diver, NAUI advanced courses',
      'Repetitive dive planning using dive tables or personally-owned dive computer',
      'Measure, record, and calculate SAC rate using SPG, depth gauge, and timer',
      'Plan a no-required-stop dive to 12–18 m (40–60 ft) including descent, bottom time, ascent, precautionary stop, and safety margin',
      'Use repetitive dive table (or personal dive computer) to plan a repetitive dive after ≥ 1 hr surface interval',
    ],
    confinedSkills: [
      // Swimming prerequisite skills (evaluated in confined water)
      'Swim 15 continuous stroke cycles demonstrating at least one recognized stroke',
      'Survival swim for 10 minutes',
      'Swim underwater 15 m (50 ft) on one breath (no push-off)',
      // Skin diving prerequisite skills (evaluated in confined water)
      'Swim 412 m (450 yd) nonstop breathing through snorkel',
      'Bring a diver simulating unconsciousness to the surface from ~3 m (10 ft) — skin diving (no scuba)',
      'Surface dives, clearing the snorkel, ditching the weight system, buoyancy control, proper entries and exits',
      // Skills marked * in NAUI 2026 S&P — must be introduced in confined water
      // Pre- and post-dive skills
      'Select, check, assemble, adjust, and don equipment; perform pre-dive gear check for self and buddy; defog mask; after diving, doff, rinse, and care for gear',
      'Perform surface buoyancy/weighting check and make adjustments as needed to hover at diving depth',
      'At the surface, remove and replace (in turn): mask, fins, and scuba unit',
      'With face submerged, breathe through snorkel while resting and swimming',
      'Regulator and snorkel exchange at the surface while swimming',
      'Surface removal and replacement of the scuba unit',
      'Demonstrate proper use of the selected weight system; remove all weight on the surface at least once; remove/replace at least one weight pocket if weight-integrated',
      // Descent/ascent skills
      'Control pressure in air spaces for comfortable, controlled descents and ascents',
      'Descend feet first with a minimum of hand movement, using breath control or BC to control rate of descent',
      // Underwater skills
      'Mask clearing, including removal and replacement',
      'Demonstrate no-mask comfort and proficiency',
      'Remove, replace, and clear a regulator',
      'Regain primary regulator from behind the shoulder, replace, and clear',
      'Environmentally appropriate buoyancy control',
      'Hover without support or significant movement',
      'Underwater swimming with position and trim appropriate to the environment',
      'Removal and replacement of the scuba unit underwater',
      'Weight system in prone position: adjust standard belt for even ballast distribution; OR remove/replace at least one weight pocket (weight-integrated)',
      // Emergency/rescue skills
      'Share air in a stationary position — be both donor and receiver via alternate air source',
      'Perform a relaxed, controlled emergency swimming ascent (ESA)',
      'Share air via octopus/alternate air source (not buddy breathing) during ascents to the surface',
      'Bring a diver simulating unconsciousness to the surface from ~3 m (10 ft); remove victim\'s weight system, mask, and snorkel; evacuate to first aid',
    ],
    openWaterSkills: [
      // Non-asterisk scuba skills
      'Correctly give and recognize surface communications',
      'Orally inflate and deflate own and buddy\'s BC',
      'Breathe through water in snorkel without choking',
      'Release a simulated muscle cramp for self and buddy',
      'Enter and exit water with dive float and "Diver Down" flag and line',
      'Deploy and retrieve a surface marker buoy (SMB)',
      'Ascend at ≤ 9 m/min (30 ft/min); execute a precautionary stop at ~4.6 m (15 ft) for 3 minutes at end of dive',
      'Give, recognize, and respond to common underwater hand signals',
      'Buddy system: stay within 3 m (10 ft) or less as required by conditions',
      'Monitor air supply; communicate amount on request; surface with pre-planned minimum air reserve',
      'Compass: set a bearing, follow the bearing, return on a reciprocal course',
      'Use environmental navigation aids; travel to a designated location or direction for a set time',
      'Measure, record, and calculate SAC rate on an actual dive using SPG, depth gauge, and timer',
      'Dive using minimal-impact techniques that promote conservation',
      'Recognize and identify (by common name) representative local plant and animal life',
      'Transport buddy simulating exhaustion for ≥ 46 m (50 yd), maintaining eye/voice contact',
      // ★ Skills applied in open water (introduced in confined water — also required in OW)
      'Select, check, assemble, adjust, and don equipment; pre-dive gear check; defog mask; post-dive doff, rinse, care',
      'Surface buoyancy/weighting check; adjust weighting to hover at diving depth',
      'At the surface, remove and replace (in turn): mask, fins, and scuba unit',
      'With face submerged, breathe through snorkel while resting and swimming',
      'Regulator and snorkel exchange at the surface while swimming',
      'Surface removal and replacement of the scuba unit',
      'Demonstrate proper use of the selected weight system; remove/replace weight as appropriate',
      'Control pressure in air spaces for comfortable, controlled descents and ascents',
      'Descend feet first with a minimum of hand movement, using breath control or BC',
      'Mask clearing, including removal and replacement',
      'Demonstrate no-mask comfort and proficiency',
      'Remove, replace, and clear a regulator',
      'Regain primary regulator from behind the shoulder, replace, and clear',
      'Environmentally appropriate buoyancy control',
      'Hover without support or significant movement',
      'Underwater swimming with position and trim appropriate to the environment',
      'Removal and replacement of the scuba unit underwater',
      'Weight system adjustment in prone position (standard belt or weight-integrated)',
      'Share air at ≥ 4.6 m (15 ft) in open water — be both donor and receiver via alternate air source',
      'Perform a relaxed, controlled emergency swimming ascent (ESA) from ≥ 4.6 m (15 ft) in open water',
      'Share air via octopus/alternate air source (not buddy breathing) during ascents from ≥ 4.6 m (15 ft) to the surface',
      'Bring a diver simulating unconsciousness to the surface from ~3 m (10 ft); remove victim\'s weight system, mask, and snorkel; evacuate to first aid',
    ],
  },
  {
    id: 'tpl_junior_ow',
    name: 'Junior Open Water Scuba Diver',
    level: 'beginner',
    description: 'Same standards as Open Water Scuba Diver (ISO 24801-2) for divers aged 10–14. Juniors must dive with a certified adult (18+). Full OW cert upon reaching age 15. Same minimums as OW: 14 hrs academic, 17 hrs total practical (≥10 water), 4 OW dives.',
    minKnowledgeHours: 14,
    trainingDiveCount: 4,
    knowledgeSkills: [
      'All Open Water Scuba Diver knowledge topics and skills apply equally',
      'Age verification: 10–14 years for Junior; full cert at age 15',
      'Must always dive with a certified adult diver (18+) — requirement noted on certification',
      'Maximum depth: 18 m (60 ft) with adult certified companion; 12 m (40 ft) without adult companion present',
      'Informed of limitations of Junior certification and encouraged to obtain full OW cert at age 15',
    ],
    confinedSkills: [],
    openWaterSkills: [],
  },
  {
    id: 'tpl_refresher',
    name: 'Scuba Refresher Experience',
    level: 'beginner',
    description: 'Skills review for certified divers returning after a period of inactivity. NAUI recommends refreshers before resuming diving after extended breaks. No new certification issued. Activities tailored to individual needs; no academic or dive minimums specified.',
    knowledgeSkills: [
      'Review dive planning and table/computer use',
      'Review emergency procedures and first aid for diving injuries',
      'Review equipment setup, function, and care',
      'Review buddy system, underwater communications, and navigation basics',
      'Assess residual knowledge gaps from previous certification level',
    ],
    confinedSkills: [
      'Equipment assembly, inspection, fit, and pre-dive gear check',
      'Proper use and adjustment of the weight system',
      'Buoyancy/weighting assessment in water; adjust as needed',
      'BC inflation and deflation (power and oral)',
      'Mask clearing (partial and full)',
      'Regulator recovery and clearing',
      'Breathe from scuba without mask',
      'Emergency swimming ascent review',
      'Air sharing drill (alternate air source)',
    ],
    openWaterSkills: [
      'Open water re-evaluation dive to verify skills meet certification level',
      'Identify any skills requiring further practice before independent diving',
    ],
  },

  // ─────────────────────────────────────────────
  // CONTINUING EDUCATION — INTERMEDIATE
  // ─────────────────────────────────────────────
  {
    id: 'tpl_aow',
    name: 'Advanced Open Water Scuba Diver',
    level: 'intermediate',
    description: 'Continuing education introducing certified divers to a variety of diving activities. Entirely open-water setting. Prereq: OW cert. Min. 6 hrs academic, 6 hrs water, 6 OW dives (3 required: navigation, night/low-vis, deep; ≥3 elective). Max depth 40 m (130 ft).',
    minKnowledgeHours: 6,
    trainingDiveCount: 6,
    knowledgeSkills: [
      'Fitness, stress, individual limitations, fatigue, exposure, and diving adaptations',
      'Rough water, limited visibility, and dive/abort decision-making',
      'Weight use, suit compression, breathing patterns, descent/ascent control',
      'Dive planning, equipment preparation, and buddy diving — each student leads at least one dive',
      'Communication, instrument use, and navigation',
      'Environmental impacts and skills that minimize environmental disturbance',
      'Rescue and assists: self and buddy — review and practice on every dive',
    ],
    confinedSkills: [],
    openWaterSkills: [
      // Required dives (3 of the 6 minimum)
      'REQUIRED — Navigation dive: compass bearings, patterns, underwater position-finding',
      'REQUIRED — Night or limited-visibility dive: lighting, signals, navigation at night',
      'REQUIRED — Deep dive to max 40 m (130 ft): gas planning, narcosis awareness, ascent rate, precautionary stop',
      // Elective dive topics (choose ≥3 to complete 6-dive minimum)
      'ELECTIVE — Search and recovery',
      'ELECTIVE — Boat diving',
      'ELECTIVE — Light salvage',
      'ELECTIVE — Hunting and collecting (where permitted)',
      'ELECTIVE — Exploration and underwater mapping',
      'ELECTIVE — Non-penetration wreck diving',
      'ELECTIVE — Observation and data collection',
      'ELECTIVE — Diving in surf or currents (drift)',
      'ELECTIVE — Altitude diving',
      'ELECTIVE — Salt water diving (if primary training is freshwater, or vice versa)',
      'ELECTIVE — Shore diving',
      'ELECTIVE — Diving for photos or video',
      'ELECTIVE — Using dive computers for planning and execution',
      // Skills
      'Demonstrate selected basic scuba skills at a proficiency higher than OW certification level',
      'Perform selected rescue and assist skills in open water',
      'Use dive tables or computer to plan all dives; record dives in logbook',
      'Navigate underwater using compass and environmental aids',
      'Use appropriate equipment for each selected activity',
      'Simulated staged decompression may be added to no-stop dive ascents (any time deeper than 7.6 m/25 ft counts toward dive time)',
    ],
  },
  {
    id: 'tpl_rescue',
    name: 'Rescue Scuba Diver',
    level: 'intermediate',
    description: 'Trains divers to manage risks and handle diving emergencies. Covers assists, transports, surface rescues, and rescues from depth. Prereq: OW cert + current BLS CPR & First Aid + Emergency O2 (EO2). Min. 4 hrs academic, 4 hrs water, 2 OW dives. Max depth 18 m (60 ft).',
    minKnowledgeHours: 4,
    trainingDiveCount: 2,
    knowledgeSkills: [
      'Causes, prevention, and treatment of diving accidents; theory of recompression therapy',
      'Barotrauma and Decompression Illness: signs, symptoms, recognition',
      'Recognizing problems due to physical conditioning and physiological factors',
      'Factors contributing to stress, the panic syndrome — in self and others',
      'Recognizing distress, overexertion, and thermal-related problems',
      'Pre-dive equipment check and equipment issues (free-flow regs, over/under-weighting, emergency ballast ditching)',
      'Surface drowning syndrome; drowning and near-drowning management',
      'Diving rescue: self-rescue, diver assists, surface and underwater rescues, diver transport',
      'Non-swimming assists and rescues; in-water rescue breathing',
      'Gear removal techniques; boat and shore extrication techniques',
      'First aid applications and emergency oxygen use',
      'Missing diver procedures and search patterns',
      'General accident management: site safety, victim care and positioning, emergency transport access, hyperbaric chamber info, accident reporting, liability',
    ],
    confinedSkills: [
      // Swimming — no equipment
      'Swim 200 m (219 yd) nonstop, any stroke',
      'Survival swim for 10 minutes',
      'Recover 4.5 kg (10 lb) object from ~3 m (10 ft) depth',
      // Skin diving
      'Swim 400 m (438 yd) nonstop breathing from snorkel',
      'Bring a diver simulating unconsciousness to the surface from ~3 m (10 ft)',
      'If ballast worn: ditch weights to establish positive buoyancy',
      // Scuba skills review
      'Assemble, adjust, don equipment; perform pre-dive equipment inspection',
      'In succession at the surface: remove and replace mask, snorkel, fins, weight system, and scuba unit',
      'Underwater: remove, replace, and clear mask and regulator in succession',
      'Breathe from regulator without mask for 2 minutes',
      'Share air using an alternate air source',
      'Demonstrate surface BC use and ability to hover underwater',
    ],
    openWaterSkills: [
      // Assists
      'Non-swimming assist from stable platform (throw bag, life ring, reaching pole)',
      'Muscle cramp removal for self and another diver',
      'Establish buoyancy at surface for self and another diver (BC power and oral, and ballast ditching)',
      'Assist a diver exhibiting breathing difficulty (suit restriction, cold, overexertion)',
      'Assist an exhausted diver using the Scuba Diver Assist technique',
      'Demonstrate diver tow using two different techniques',
      'Assist a panicking diver at the surface and underwater',
      'Share air as both donor and receiver from alternate air source during ascents',
      'Conduct a lost-diver search using a search pattern appropriate for the underwater environment',
      'With one assistant: remove a non-breathing unconscious diver from the water at shore, boat, or platform',
      // Scuba Diver Rescue scenario
      'Make an entry and swim ≥ 20 m (21 yd) to simulated victim; retrieve victim from 6–9 m (20–30 ft) using controlled ascent; establish buoyancy, signal for help, manage gear while transporting to exit',
      'Perform simulated in-water rescue breathing on surfaced victim',
      'Demonstrate situational awareness to determine when rescue breathing is beneficial',
      // Full rescue scenario
      'Apply full Scuba Diver Rescue sequence in real-time scenario',
      'Apply Accident Management Plan',
      'Administer emergency oxygen to rescue victim',
    ],
  },
  {
    id: 'tpl_master',
    name: 'Master Scuba Diver',
    level: 'intermediate',
    description: 'Advanced continuing education with strong emphasis on practical open-water application. Prereq: Advanced OW cert + Rescue Scuba Diver. Min. 23 hrs academic, 8 hrs water, 8 OW dives (5 required + 3 elective). Max depth 40 m (130 ft).',
    minKnowledgeHours: 23,
    trainingDiveCount: 8,
    knowledgeSkills: [
      'Applied sciences review: physics, physiology, medical aspects, fitness — applied to buoyancy, pressure changes, air consumption, personal limitations',
      'Equipment: detailed functioning, care, specialized gear used in Master-level activities; technical scuba mechanics overview',
      'Diving safety: rescue, first aid, emergency procedures; underwater comms, navigation, dive planning; emergency O2 benefits; first aid for shock, wounds, drowning, heart attack, fractures, hypothermia, lung overexpansion, DCS, seasickness',
      'Rescue: problem recognition, diver assists, rescues, in-water rescue breathing, transports, carries, CPR orientation',
      'Diving environment: plant and animal identification, relationships, dangers, regulations, conservation, pollution, water movement, shore/bottom/surface conditions, diving locations',
      'Underwater navigation: compass, natural aids for orientation, setting relative position, swimming prescribed directions, finding locations submerged and at surface',
      'Night and limited-visibility diving: problems, techniques, skill levels, hazards, and safety procedures',
      'Search, recovery, and light salvage: selecting search pattern, conducting search with proper technique; recovery of intermediate-sized objects with limited equipment; rigging, calculations, and principles',
      'Deep and simulated decompression diving (18–40 m / 60–130 ft): anticipating and preventing problems; thorough knowledge of dive tables',
    ],
    confinedSkills: [],
    openWaterSkills: [
      // Required dives (5 of the 8 minimum)
      'REQUIRED — Emergency procedures and rescue dive',
      'REQUIRED — Deep/simulated decompression dive to max 40 m (130 ft)',
      'REQUIRED — Limited visibility or night dive',
      'REQUIRED — Underwater navigation dive',
      'REQUIRED — Search and recovery / light salvage dive',
      // Elective dives (3 to complete 8-dive minimum)
      'ELECTIVE — Skin diving',
      'ELECTIVE — Review of basic scuba skills',
      'ELECTIVE — Environmental study or survey',
      'ELECTIVE — Practical air consumption dive',
      'ELECTIVE — Boat diving',
      'ELECTIVE — Shore diving',
      'ELECTIVE — Hunting and collecting (where permitted)',
      'ELECTIVE — Special interest dive chosen by class',
      // Skills
      'Perform all skills at a level significantly higher than at previous certification levels',
      'Use greatest possible variety of diving sites (boat, shore, dock; lake, ocean, quarry, river; surf or current; varied bottom types)',
      'Each diver assumes a leadership role on at least one dive',
      'Record all dives in a logbook; prepare and present dive plans for each site/activity',
    ],
  },

  // ─────────────────────────────────────────────
  // SPECIALTY COURSES
  // ─────────────────────────────────────────────
  {
    id: 'tpl_nitrox',
    name: 'Enriched Air Nitrox (EANx) Diver (ISO 11107)',
    level: 'intermediate',
    description: 'Trains certified divers to use EANx mixtures up to EAN40. May be taught standalone or integrated into another NAUI course. Prereq: OW cert (or concurrent enrollment). Min. 2 hrs academic, 2 hrs water; 2 OW dives strongly encouraged (1 must be repetitive). Max ppO₂: 1.4 (1.6 deco).',
    minKnowledgeHours: 2,
    trainingDiveCount: 2,
    knowledgeSkills: [
      'EANx (enriched air nitrox) advantages and disadvantages vs. air',
      'EANx risks: oxygen toxicity (CNS and pulmonary), O2 partial pressure limits',
      'Hazards and precautions of handling oxygen and oxygen-enriched gas',
      'Maximum Operating Depth (MOD) calculation for any EANx mix',
      'Equivalent Air Depth (EAD) calculation',
      'Use of EANx with standard air tables, EANx tables, or RGBM/computer-based planning',
      'Using a personally-owned nitrox-capable dive computer (acceptable alternative to tables)',
      'Common gas mixing procedures',
      'Gas analyzing procedures (how to use an O2 analyzer)',
      'ODIGTML dive planning format: Oxygen, Decompression, Inert Gas Narcosis, Gas Management, Thermal, Mission, Logistics',
    ],
    confinedSkills: [
      'Demonstrate complete ODIGTML dive planning for EANx dives',
      'Demonstrate the ability to analyze breathing gas using an O2 analyzer',
      'Label, document, and verify EANx cylinders before use',
    ],
    openWaterSkills: [
      'Plan and safely execute 2 dives using EANx — one must be a repetitive dive',
      'Analyze own breathing mixture before each dive',
      'Adhere strictly to EANx dive plan (especially MOD limits)',
    ],
  },
  {
    id: 'tpl_deep',
    name: 'Deep Diver',
    level: 'intermediate',
    description: 'Knowledge and skills to plan and make deep dives (18–40 m / 60–130 ft) while minimizing risks and avoiding staged decompression. Prereq: Advanced Open Water Scuba Diver (or equivalent). Min. 2 hrs academic, 2 hrs water, 2 OW dives. Max depth 40 m (130 ft).',
    minKnowledgeHours: 2,
    trainingDiveCount: 2,
    knowledgeSkills: [
      'Deep diving defined: 18–40 m (60–130 ft) for recreational purposes',
      'Gas planning for deep dives: supply, consumption at depth, reserve requirements',
      'Nitrogen narcosis: recognition, effects, response, personal susceptibility',
      'Deep dive physiology: O2 partial pressure, increased gas density, thermal exposure',
      'No-decompression limit planning and contingency for simulated staged decompression',
      'Ascent rates and precautionary stop discipline at depth',
      'Equipment considerations for deep diving',
    ],
    confinedSkills: [],
    openWaterSkills: [
      'Plan and execute a deep dive to max 40 m (130 ft) with no required staged decompression',
      'Assess narcosis effects and signal buddy/ascend if impaired',
      'Manage gas supply from surface; surface with planned minimum air',
      'Perform controlled ascent at ≤ 9 m/min (30 ft/min); execute safety stop',
      'Simulated staged decompression may be added to ascent; time deeper than 7.6 m (25 ft) counts in dive time',
      'Buddy communication and awareness at depth',
      'Record dive including depth, bottom time, gas usage, and narcosis observations in logbook',
    ],
  },
  {
    id: 'tpl_night',
    name: 'Night & Limited-Visibility Diver',
    level: 'intermediate',
    description: 'Skills and knowledge to minimize risk while diving at night or in limited visibility. May be taught as a scuba or skin diving course. Prereq: Scuba Diver (ISO 24801-1) or equivalent for scuba; Skin Diver for skin-diving version. Min. 2 hrs academic, 2 hrs water, 2 OW dives. Max depth 40 m (130 ft).',
    minKnowledgeHours: 2,
    trainingDiveCount: 2,
    knowledgeSkills: [
      'Night diving physiology: reduced vision, disorientation, altered sense of depth',
      'Night dive planning: site selection, entry/exit points, abort criteria, communication plan',
      'Lighting equipment: primary, backup, and marker lights — specifications and care',
      'Underwater light communication signals and signals visible to the surface',
      'Nocturnal marine behavior: species active at night, feeding behavior, camouflage',
      'Environmental considerations: impact reduction at night, reef-safe techniques',
    ],
    confinedSkills: [],
    openWaterSkills: [
      'Assemble, test, and carry all required lights before the dive',
      'Pre-dive orientation to the site during daylight (if first night dive at site)',
      'Entry and exit in darkness using appropriate technique',
      'Underwater navigation at night using compass, light signals, and environmental cues',
      'Maintain close buddy contact (arm\'s reach or light-contact distance) throughout dive',
      'Light communication signals underwater and at the surface',
      'Diver separation procedures: signal for attention, ascend to surface and signal',
      'Light failure emergency procedure: backup light deployment, controlled ascent if needed',
      'Encounter and observe nocturnal marine life without disturbing habitat',
    ],
  },
  {
    id: 'tpl_ice',
    name: 'Recreational Ice Diver',
    level: 'advanced',
    description: 'Knowledge and skills for diving under ice. Prereq: Advanced OW Scuba Diver + 50 logged dives (varied conditions). Min. age 18. Instructor must be a certified NAUI Ice Diver with 25+ ice dives. Max 2 students per instructor in water. Min. 8 hrs academic, 3 OW dives. Max depth 12 m (40 ft) under ice; max 30 m horizontal from hole; max 2 training dives/day.',
    minKnowledgeHours: 8,
    trainingDiveCount: 3,
    knowledgeSkills: [
      'Fresh water diving physics: density, thermoclines, visibility, cold stress',
      'Purpose, planning, and organization of ice dives; site assessment and hazard identification',
      'Gas management in cold and overhead environments; rule of thirds vs. thirds-modified',
      'Special risks of overhead environments: lost line, regulator free-flow/freeze, entanglement',
      'Cold-water physiology: cold shock, hypothermia, cold-induced incapacitation',
      'Required additional personnel: tender, safety diver, surface support team roles',
      'Equipment specific to ice diving: redundant cylinders, cold-water rated regulators, safety harness, line systems',
      'Line-tending signals and communication protocols (surface–diver line signals)',
      // Equipment requirements
      'Redundant primary cylinder (≥80 cu ft / 2265 L) + bailout bottle (≥19 cu ft / 538 L)',
      'Cold-water rated regulators; test regulator function in cold water before entry',
      '¼-inch (6 mm) floating guideline with distance markings; reel/spool operation',
      'Minimum 2 redundant underwater lights; minimum 2 line-cutting devices',
      'Separate safety harness with secure line attachment (BC harness NOT used as safety harness)',
      'O2 analyzer if EANx used',
    ],
    confinedSkills: [],
    openWaterSkills: [
      'Ice entry preparation: hole safety, ice thickness verification, entry assist',
      'Line-tending signals with surface tender: established communication protocol',
      'Under-ice guideline deployment, following, and retrieval',
      'Guideline following with touch contact in simulated zero visibility',
      'Regulator free-flow procedure: shut-down and switch to bailout',
      'Buddy separation protocol: signal, surface via line, reunite plan',
      'Lost line procedure: halt, buddy check, find line, or controlled ascent to ice underside',
      'Emergency ascent under ice to breathing pocket; surface via hole using tender',
      'Post-dive: equipment function check, de-icing procedures',
    ],
  },
  {
    id: 'tpl_search',
    name: 'Search and Recovery Diver',
    level: 'intermediate',
    description: 'Skills and knowledge to search for and recover lost objects in the aquatic environment. Prereq: Scuba Diver (ISO 24801-1) or equivalent. Min. 3 hrs academic, 2 hrs water, 2 OW dives. Max depth 40 m (130 ft).',
    minKnowledgeHours: 3,
    trainingDiveCount: 2,
    knowledgeSkills: [
      'Search pattern selection criteria based on visibility, current, bottom type, and object size',
      'Jackstay (parallel) search pattern — setup and execution',
      'Circular (expanding) search pattern — setup and execution',
      'Expanding square search pattern — setup and execution',
      'Lost object procedures: marking the probable location, using surface reference',
      'Subsurface marking: lift bag deployment, SMB/DSMB use',
      'Light salvage theory: hazards, methods, rigging, knot tying, buoyancy calculations',
      'Lift bag sizing: how to calculate required lift volume for object recovery',
    ],
    confinedSkills: [],
    openWaterSkills: [
      'Conduct a jackstay search using a line and reel',
      'Conduct a circular or expanding-square search using a line and reel',
      'Deploy a lift bag from depth; control ascent rate to avoid runaway lift',
      'Rig an object for recovery using appropriate knots and rigging',
      'Recover small-to-intermediate objects with limited equipment',
      'Maintain neutral buoyancy and environmental awareness while conducting search',
      'Record findings: underwater sketch or written description of object location',
    ],
  },
  {
    id: 'tpl_drysuit',
    name: 'Drysuit Diver',
    level: 'intermediate',
    description: 'Training in drysuit use for cold-water diving. Prereq: OW Scuba Diver (or concurrent enrollment). Instructor must be certified NAUI Drysuit Diver with ≥25 drysuit dives. Min. 1 hr academic, 2 hrs confined water, 4 OW dives. Max depth 40 m (130 ft).',
    minKnowledgeHours: 1,
    minConfinedWaterHours: 2,
    trainingDiveCount: 4,
    knowledgeSkills: [
      'Drysuit types: membrane, neoprene, trilaminate — features and applications',
      'Thermal undergarment selection for water temperature',
      'Drysuit valves: inflator and dump valve — location, function, maintenance',
      'Buoyancy management: using drysuit air vs. BC air; proper integrated use',
      'Cold-water physiology and thermal protection principles',
    ],
    confinedSkills: [
      'Donning and doffing the drysuit; zipper care and sealing',
      'Pre-dive valve and seal inspection; zipper lubrication',
      'Identify and operate all suit controls (inflator, dump valve, wrist/neck seals)',
      'Establish neutral buoyancy in drysuit: coordinate suit inflation with BC',
      'Manage suit air during descent: add air to prevent squeeze',
      'Manage suit air during ascent: vent suit to prevent uncontrolled ascent',
    ],
    openWaterSkills: [
      'Recover from inverted position (suit blowup): roll to vertical, dump excess air via dump valve',
      'Recover from simulated stuck dump valve: use backup vent position',
      'Demonstrate procedure to compensate for jettisoned weight system while in drysuit',
      'Select a compatible buoyancy compensator for drysuit diving',
      'Maintain minimum suit air to prevent suit squeeze',
      'Conduct a minimum of 4 open water dives in drysuit demonstrating all skills',
    ],
  },
  {
    id: 'tpl_naturalist',
    name: 'Underwater Naturalist Diver',
    level: 'intermediate',
    description: 'Exposes divers to physical and biological aspects of the dive environment with emphasis on local ecosystems (kelp forest, coral reef, or freshwater). Day and night dives encouraged. Divemaster may co-teach with written NAUI Training Dept. approval. Min. 2 hrs academic, 2 hrs water, 2 OW dives. Max depth 40 m (130 ft).',
    minKnowledgeHours: 2,
    trainingDiveCount: 2,
    knowledgeSkills: [
      'General morphology of kelp forests, coral reefs, or freshwater environments (as applicable locally)',
      'Reef zones or aquatic zone structure and organisms by zone',
      'Survey methods for determining population densities of selected species',
      'Plant and animal identification: selected local species — relationships, dangers, regulations, and uses',
      'Conservation and pollution: current problem areas and possible solutions',
      'Water movement and characteristics: tides, currents, waves, surf, temperature, pressure, density, visibility, salinity, and sound',
      'Shore, bottom, and surface conditions: features, hazards, natural navigation aids, wind effects',
      'Diving locations: use of charts, planning dives; sources of environmental information',
      'Behavior of vertebrate and invertebrate species (e.g., diurnal vs. nocturnal, seasonal, feeding, territory)',
      'Zero-contact diving etiquette: buoyancy control over reef/substrate to prevent damage',
      'Impacts of touching, collecting, anchoring on sensitive environments',
      'Sustainable dive practices and NAUI Green Diver Initiative',
      'Locally protected species identification and regulations',
    ],
    confinedSkills: [],
    openWaterSkills: [
      'Dive using skills that have minimal impact on the environment',
      'Identify (by common name) representative plants, fish, and invertebrates encountered',
      'Conduct day and night observation dives in the same area (if conditions permit)',
      'Record species observed; use appropriate citizen-science data collection if applicable',
    ],
  },
  {
    id: 'tpl_photographer',
    name: 'Underwater Digital Imaging Diver',
    level: 'intermediate',
    description: 'Skills and knowledge to enjoy underwater photography and/or videography while minimizing risk. Focuses on imaging techniques, situational awareness, and environmental responsibility. Divemaster may teach with written NAUI Training Dept. approval. Prereq: Scuba Diver (ISO 24801-1) or equivalent. Min. 2 hrs academic, 2 hrs water, 2 OW dives. Max depth 40 m (130 ft).',
    minKnowledgeHours: 2,
    trainingDiveCount: 2,
    knowledgeSkills: [
      'Underwater photography and/or videography equipment overview: camera housings, ports, controls',
      'Photo and video composition techniques: wide-angle, macro, framing, rule of thirds',
      'Lighting techniques: strobe positioning, video light use, color correction at depth',
      'Fundamentals of photography/videography: exposure, aperture, shutter speed, ISO (for cameras with manual control)',
      'Underwater camera and video techniques: approach, movement, focus underwater',
      'Environmental photography ethics: zero-contact approach, no baiting or disturbing subjects',
      'Underwater problem resolution: flooded housing, lost focus, battery management',
      'Post-dive equipment care: rinsing housing, o-ring inspection and lubrication',
    ],
    confinedSkills: [
      'Dive planning: account for camera/housing transport, buoyancy adjustment for equipment',
      'Proper water entry with imaging equipment to prevent flooding',
    ],
    openWaterSkills: [
      'Monitor air supply continuously while operating camera',
      'Track depth and no-stop time while operating camera',
      'Maintain buoyancy control (no contact with substrate) while imaging',
      'Maintain awareness of environmental hazards and dive buddy proximity while imaging',
      'Approach subjects without physical contact or reef damage',
      'Actually capture and review underwater photographs and/or video footage',
      'Post-dive critique of images/footage with instructor for technique improvement',
    ],
  },
  {
    id: 'tpl_altitude',
    name: 'Altitude Diver',
    level: 'intermediate',
    description: 'Skills and knowledge to minimize risks when diving at altitude (above 300 m / 1000 ft). Taught entirely in an open water setting at altitude. Prereq: OW Scuba Diver or concurrent enrollment. Instructor must be certified NAUI Altitude Diver with NAUI Training Dept. authorization. Min. 2 hrs academic, 4 hrs water, 2 OW dives at altitude. Max 2 dives/day; max depth 40 m (130 ft) SLE.',
    minKnowledgeHours: 2,
    trainingDiveCount: 2,
    knowledgeSkills: [
      'Altitude diving defined: any dive above 300 m (1000 ft) elevation',
      'Altitude physiology: reduced atmospheric pressure, accelerated off-gassing implications',
      'Theoretical Ocean Level (TOL) concept and how to calculate TOL for a given altitude',
      'No-decompression limit adjustments at altitude using dive tables or an altitude-capable dive computer',
      'Safety stop depth adjustment: determine appropriate safety stop depths for three different altitudes',
      'Flying after altitude diving: compounded off-gassing considerations',
      'Altitude dive planning using ODIGTML format: Oxygen, Decompression, Inert Gas Narcosis, Gas Management, Thermal, Mission, Logistics',
      'Emergency procedures specific to altitude environments (access to recompression may be remote)',
    ],
    confinedSkills: [],
    openWaterSkills: [
      'Plan and execute minimum of 2 dives at altitude using altitude-corrected tables or an altitude-capable dive computer',
      'Determine no-decompression limits for the altitude of the dive site',
      'Determine appropriate safety stop depths for the altitude of the dive site',
      'Adjust descent/ascent rates and safety stop duration for altitude conditions',
      'Record dive: altitude, corrected NDLs, depths, times, surface intervals',
    ],
  },
  {
    id: 'tpl_wreck',
    name: 'Wreck Diver (External Survey)',
    level: 'intermediate',
    description: 'Skills and knowledge for external survey wreck diving — diving around a sunken vessel, aircraft, or debris field. No penetration of overhead spaces. Prereq: Advanced Open Water Scuba Diver or equivalent. Min. 3 hrs academic, 3 hrs water, 3 OW dives. Max depth 40 m (130 ft).',
    minKnowledgeHours: 3,
    trainingDiveCount: 3,
    knowledgeSkills: [
      'Wreck diving defined: external survey (around wreck, not inside overhead spaces)',
      'Wreck diving hazards: entanglement, sharp metal and glass, sudden deterioration/collapse, disorientation',
      'Environmental impact of wrecks: artificial reef ecology, protection considerations, artifact laws',
      'Wreck survey planning: site research, depth, current, visibility, descent/ascent options',
      'Gas management during wreck dives: reserves, impact of bottom time at depth',
      'Buoyancy control near delicate and fragile surfaces: prevent silting and contact',
      'Finning techniques to avoid disturbing silt near wrecks',
    ],
    confinedSkills: [],
    openWaterSkills: [
      'Pre-dive planning: review wreck layout, identify hazards, plan entry and exit',
      'Descent to wreck using mooring line, shotline, or controlled descent to bottom',
      'External survey: systematic swim pattern around wreck exterior to map/observe',
      'Maintain proper trim and buoyancy to avoid contact with wreck surfaces',
      'Use torch/light for visual inspection of shaded exterior areas',
      'Identify and avoid entanglement hazards (monofilament, nets, cables)',
      'Ascent and safety stop: use mooring line or SMB/DSMB for controlled ascent',
      'Record wreck observations in logbook (location, depth, features, marine life observed)',
    ],
  },
  {
    id: 'tpl_citizen_science',
    name: 'Citizen Science Diver',
    level: 'intermediate',
    description: 'Trains certified divers to conduct underwater surveys for recognized citizen science organizations. Prereq: Advanced OW Scuba Diver + Rescue Scuba Diver (Nitrox strongly recommended). Instructor must have ≥1 year scientific diving experience and NAUI Training Dept. authorization. Min. 20 hrs academic, 6 hrs water, 4 OW dives. Max depth 30 m (100 ft).',
    minKnowledgeHours: 20,
    trainingDiveCount: 4,
    knowledgeSkills: [
      'Introduction to citizen science: organizations, programs, and their conservation value',
      'Sampling protocol for the survey method used in the course (e.g., REEF, CoralWatch, iNaturalist)',
      'Data reporting procedures: how and where to submit survey data to the citizen science organization',
      'Requirements for advancement/recognition within the citizen science organization',
      'Species identification techniques: local fish, invertebrate, and algae species',
      'Survey site layout: transect/plot setup, data entry, quality assurance/quality control',
      'Coastal ecology relevant to the survey environment (reef, kelp, freshwater, seagrass, etc.)',
      'NAUI Green Diver Initiative: minimizing environmental impact during science dives',
      'Fitness, stress, individual limitations, exposure, and diving adaptations during scientific work',
      'Rough water, limited visibility, and dive/abort decision-making for science dives',
      'Rescue review: self and buddy assists; emergency systems',
    ],
    confinedSkills: [],
    openWaterSkills: [
      'Use ODIGTML dive planning format for all science dives',
      'Prepare and present a dive plan for each site/survey purpose',
      'Deploy and set up transect line or survey plot underwater',
      'Conduct species count or other protocol while maintaining buoyancy, depth, time, and buddy awareness',
      'Complete data slate accurately during the dive',
      'Debrief and record dives in logbook with survey data',
      'Submit data to the relevant citizen science organization',
    ],
  },

  // ─────────────────────────────────────────────
  // ADVANCED / TECHNICAL-PREREQUISITE COURSES
  // ─────────────────────────────────────────────
  {
    id: 'tpl_cavern',
    name: 'Cavern Diver',
    level: 'advanced',
    description: 'Diving in cavern zones within natural light without full penetration. Prereq: Advanced OW Scuba Diver. Min. age 18. Instructor must be NAUI Cave II + 100 cave dives + NAUI Cavern Instructor workshop. Max depth 30 m (100 ft). Technical-level course. Min. 8 hrs academic, 1 OW skill development dive + 6 cavern dives (7 total); min. 120 min overhead time; ≥2 different caverns.',
    minKnowledgeHours: 8,
    trainingDiveCount: 7,
    knowledgeSkills: [
      'ODIGTML dive planning for overhead environments: Oxygen, Decompression, Inert Gas Narcosis, Gas Management, Thermal, Mission, Logistics',
      'Cavern diving limits: the cavern zone — always within sight of natural light, guideline to exit',
      'Cavern environment: geology and formation types, entrance types, terminology',
      'General and specific hazards: siltout, line traps, flow reversals, lost guideline, psychological stress',
      'One Breath Concept: gas rule for overhead environments (thirds; entry + buffer)',
      'Trim, propulsion, and streamlining for zero-disturbance diving',
      'Guideline protocols: primary line, jump/gap lines, permanent vs. temporary guidelines',
      'Communications: line-pull signals, light signals, touch contact in zero visibility',
      'Dive team protocols: lead/back position, roles, etiquette',
      'Emergency problems, solutions, and procedures',
      'Conservation and landowner relations',
      'Accident analysis relevant to cavern diving',
      // Equipment requirements (knowledge)
      'Primary regulator on 213 cm (84 in) hose',
      'Primary reel/spool ≥ 60 m (200 ft) per team + safety reel 30 m (100 ft) per team member',
      'Starting gas volume ≥ 1415 L (50 cu ft) for cavern dives',
      'Minimum 1 line-cutting device; minimum 2 battery-powered diving lights',
      'Appropriate thermal protection; 2 decompression calculation methods',
    ],
    confinedSkills: [
      // Land drills (before entering water)
      'Demonstrate proficiency in spool/reel, lights, and long hose',
      'Demonstrate appropriate team position and responsibilities',
      'Demonstrate line protocols and placement on land',
      'Demonstrate touch-contact communication while following simulated guideline in zero-vis',
      'Emergency protocols practice on land before entering water',
    ],
    openWaterSkills: [
      // Open water skill development (1 OW dive)
      'Follow guideline without mask (comfortable open-water demonstration)',
      'Follow guideline with touch contact while sharing gas in simulated zero visibility',
      'Hover with proper buoyancy and trim without swimming or sculling',
      'Demonstrate frog kick, modified frog, modified flutter, and pull-and-glide propulsion',
      'Demonstrate 360-degree rotation with appropriate trim',
      // Cavern skills (6 cavern dives)
      'Guideline deployment and removal techniques inside the cavern',
      'Gas management with rule of thirds in overhead environment',
      'Navigate cavern on guideline and return to exit',
      'Simulated emergency procedures inside cavern zone (lost line, gas sharing)',
    ],
  },
  {
    id: 'tpl_sidemount',
    name: 'Sidemount Diver',
    level: 'advanced',
    description: 'Fundamental knowledge and skills for open water diving in sidemount configuration within no-decompression limits. Prereq: Advanced OW Scuba Diver + Nitrox Diver + ≥25 logged dives. Instructor must be NAUI Sidemount Diver with ≥50 sidemount dives. Min. 4 hrs academic; CW skills required before any OW dive; 4 OW dives. Max depth 40 m (130 ft; not deeper than 18 m until skills checklist complete).',
    minKnowledgeHours: 4,
    trainingDiveCount: 4,
    knowledgeSkills: [
      'NAUI equipment configuration for sidemount: harness, bungees, hip rings, D-rings',
      'Cylinder attachment considerations: stage positioning, clip placement, routing of hoses',
      'Ballasting and buoyancy control in sidemount configuration vs. backmount',
      'Water entry and exit procedures specific to sidemount (cylinders attached before or after?)',
      'Cylinder removal and replacement procedures: on surface, in water, at depth',
      'Gas management with independent cylinders: alternating regulators to equalize gas',
      'Gas sharing procedures with sidemount cylinders',
      'Psychological aspects of sidemount diving: task loading, comfort, pre-dive planning',
      'ODIGTML Dive Planning format: Oxygen, Decompression, Inert Gas Narcosis, Gas Management, Thermal, Mission, Logistics',
      // Pre-dive safety drills (before every dive)
      'Equipment checks (cylinders secure, valves open, regs functioning)',
      'Bubble check at the surface before descent',
      'Gas sharing drill at the surface',
      'Dive plan and limits review with buddy',
    ],
    confinedSkills: [
      // All CW skills must be completed before any OW dive
      'Attach sidemount cylinders: out of water, standing in shallows, on surface in deep water',
      'Demonstrate environmentally appropriate propulsion techniques',
      'Remove, replace, and clear mask in sidemount configuration',
      'Out-of-air drill: share air with buddy at depth in neutral position, perform safe ascent to surface',
      'Bring a diver simulating unconsciousness to the surface from ~3 m (10 ft); simulate in-water rescue breathing',
      'Hover with proper horizontal body position without swimming',
      'With a simulated out-of-gas teammate: swim ≥ 30 m (100 ft) underwater while sharing gas',
    ],
    openWaterSkills: [
      'Demonstrate simulated regulator failure: shut-down and switch-over within 10 seconds',
      'Demonstrate adequate trim and proper body position throughout descent, bottom, and ascent',
      'Unclip sidemount cylinder, rotate 1 and 2 cylinders to front and back and reattach',
      'Safely manage gas in independent cylinders throughout dive (alternate every 100 psi or per plan)',
      'Remove and replace sidemount cylinders at depth',
      'Conduct minimum 4 open water dives demonstrating all sidemount skills',
    ],
  },

  // ─────────────────────────────────────────────
  // PROFESSIONAL COURSES
  // ─────────────────────────────────────────────
  {
    id: 'tpl_divemaster',
    name: 'Divemaster (ISO 24801-3)',
    level: 'professional',
    description: 'Highest NAUI leadership certification below Instructor. Qualifies holders to organize and conduct open water dives for certified divers and assist instructors during training. Prereq: OW + Rescue + Nitrox + Master Scuba Diver + First Aid for Dive Pros (DFA Pro) + 60 logged dives with 30 hrs bottom time. Min. 20 hrs academic (≥15 instructor-supervised), 20 hrs water; min. 20 DM activities over ≥10 dives. Max depth 40 m (130 ft).',
    minKnowledgeHours: 20,
    knowledgeSkills: [
      // Academic knowledge (20 hrs — at least 15 must be instructor supervised)
      'Dive theory: physics, physiology, equipment, environment, decompression theory',
      'NAUI Standards and Policies: course requirements, instructor responsibilities, liability principles',
      'Risk management: hazard identification, risk assessment, emergency planning',
      'Legal aspects of professional diving supervision and liability',
      'Marketing and professional skills: prospecting students, organizing courses, budgeting',
      // Teaching presentations (4 required from 10 core knowledge topics)
      'Classroom teaching presentation 1 — selected from 10 core diving knowledge topics',
      'Classroom teaching presentation 2 — selected from 10 core diving knowledge topics',
      'Classroom teaching presentation 3 — selected from 10 core diving knowledge topics',
      'Classroom teaching presentation 4 — at least 1 presentation must receive a passing grade on evaluation',
      // Divemaster duties
      'Techniques for planning, organizing, and controlling a group dive',
      'Site analysis, selection, and pre-dive evaluation',
      'Pre-dive meeting and briefing preparation and delivery',
      'Debriefing technique and constructive critique',
      'Divemaster checklists and logbooks',
      'Use of safety divers and assistants',
      'Dive flag use; special procedures for leading excursions and working with instructors',
      'Escorting and overseeing certified divers on dives',
    ],
    confinedSkills: [
      // Water skills — must demonstrate proficiency
      'Swim 400 m (438 yd) nonstop — any stroke',
      'Survival float/swim for 15 minutes',
      'Skin diving: swim 400 m (438 yd) nonstop, bring unconscious diver from 3 m (10 ft)',
      'Scuba: demonstrate all OW Scuba Diver skills proficiently (mask clearing and removal/replacement; regulator remove/replace/clear; regain primary regulator; neutral buoyancy)',
      'Complete a night dive as a diver (staff demonstrates night dive organization during this dive)',
    ],
    openWaterSkills: [
      // Rescue scenario
      'Perform, as Divemaster with safety divers and assistants, a complete rescue of a diver simulating an underwater accident in open water: organize search, transport victim to shore/boat, victim care, access emergency systems',
      // Briefings
      'Prepare and present ≥1 pre-dive briefing for practice and ≥1 evaluated briefing',
      'Evaluated briefing graded on depth of coverage, safety emphasis, and clarity',
      // OW activities (minimum 20 over at least 10 dives)
      'Conduct ≥20 Divemaster activities over ≥10 open water dives (on-site instruction, skill demonstrations, escorting/touring)',
    ],
  },
  {
    id: 'tpl_instructor',
    name: 'Open Water Scuba Instructor (ISO 24802-2)',
    level: 'professional',
    description: 'NAUI Instructor Training Course (ITC). Trains and qualifies NAUI Instructor candidates in effective methods to teach diving per NAUI standards. May be presented in two phases (ITP + IE). Prereq: Active Divemaster (or equivalent) + current Rescue + Nitrox + DFA Pro (First Aid for Dive Professionals). Must pass NAUI Instructor Final Exam + 5 Instructor Knowledge Exams. Min. 85 hrs academic (35 supervised by IT/CD; 50 direct/RPL/eLearning/self-study), 15 hrs in-water (all supervised by IT/CD), min. 3 OW training days. Max depth 40 m (130 ft).',
    minKnowledgeHours: 85,
    knowledgeSkills: [
      // Academic / professional modules
      'ITC orientation: course structure, evaluation criteria, standards overview',
      'Student-centered learning and NAUI teaching methodology',
      'Effective classroom presentation skills: voice, visuals, interaction, timing',
      'Effective confined water instructional presentation: skill introduction, feedback, correction',
      'Effective open water instructional presentation: briefing, supervision, debriefing',
      'Teaching physics, physiology, and equipment modules',
      'Teaching the 10 core diving knowledge topics',
      'Lesson planning and course scheduling per NAUI standards',
      'Prospecting and recruiting students; organizing and budgeting courses',
      'Marketing: CE courses, leadership courses, and equipment',
      'NAUI marketing tools and member resources',
      'Legal aspects of diving instruction: liability, risk management, professional responsibility',
      'Standards and policies: conducting courses within NAUI S&P; academic freedom',
      'Certification requirements: when and how to certify; Provisional status',
      'NAUI App, NAUI Core, and administrative tools',
      // Knowledge examinations (must pass all 5; one retry allowed per exam)
      'EXAM — Diving Environments',
      'EXAM — NAUI Standards and Policies',
      'EXAM — Dive Rescue',
      'EXAM — Nitrox',
      'EXAM — Dive Skills and Practices',
      'EXAM — NAUI Instructor Final Examination',
    ],
    confinedSkills: [
      'Confined water presentation 1: introduce and teach an OW Scuba Diver skill',
      'Confined water presentation 2: introduce and teach an OW Scuba Diver skill',
    ],
    openWaterSkills: [
      'Open water presentation 1: conduct a dive briefing, supervise, and debrief',
      'Open water presentation 2: conduct a dive briefing, supervise, and debrief',
      'Assist with or deliver a supervised NAUI OW Scuba Diver course component',
      'Demonstrate all OW Scuba Diver skills proficiently to IE/Instructor Trainer standard',
      'Pass final review board (if applicable)',
    ],
  },

  // ─────────────────────────────────────────────
  // FIRST AID COURSES (NAUI Powered by DAN)
  // ─────────────────────────────────────────────
  {
    id: 'tpl_bls',
    name: 'Basic Life Support (BLS) CPR & First Aid',
    level: 'beginner',
    description: 'NAUI Powered by DAN. Develops CPR skills and first aid knowledge for diving professionals and divers. A prerequisite for NAUI Rescue Scuba Diver and all leadership courses. Certification expires 2 years from completion. Min. 2–3 hrs academic, 4–6 hrs skills, 6–9 hrs total. No in-water dives required.',
    minKnowledgeHours: 2,
    knowledgeSkills: [
      'Basic life support (BLS) principles',
      'Medical emergencies relevant to diving and recreational activities',
      'Respiration and circulation: anatomy overview',
      'Scene safety assessment',
      'Initial assessment: responsiveness, breathing, circulation',
    ],
    confinedSkills: [
      // CPR skills
      'Adult, child, and infant CPR (1-rescuer and 2-rescuer)',
      'Hands-only CPR technique',
      'Rescue breathing with barrier device (pocket mask, face shield)',
      'CPR with AED integration',
      // AED
      'AED operation: power on, pad placement, analyze, shock delivery',
      'AED maintenance and readiness checks',
      // First Aid
      'Scene safety and personal protective equipment (PPE)',
      'Shock recognition and management',
      'Bleeding control: direct pressure, wound packing',
      'Tourniquet application',
      'Fracture and spinal injury management',
      'Burns, heat and cold emergencies',
      'Medical emergencies: chest pain, stroke, diabetic emergencies, anaphylaxis',
      'Recovery position for unconscious breathing victim',
      'Accessing emergency medical services (EMS)',
    ],
    openWaterSkills: [],
  },
  {
    id: 'tpl_eo2',
    name: 'Emergency Oxygen for Scuba Diving Injuries (EO2)',
    level: 'beginner',
    description: 'NAUI Powered by DAN. Teaches emergency oxygen administration for diving injuries. A prerequisite for NAUI Rescue Scuba Diver and leadership courses. Certification expires 2 years from completion. Min. 1–2 hrs academic, 3–4 hrs skills, 6 hrs total. No in-water dives required.',
    minKnowledgeHours: 1,
    knowledgeSkills: [
      'Atmospheric gases and oxygen physiology',
      'Respiration and circulation as they relate to oxygen administration',
      'Decompression illness: DCS and arterial gas embolism (AGE) — causes, symptoms, recognition',
      'Oxygen and diving injuries: why O2 first aid is beneficial',
      'Handling oxygen safely: cylinder, regulator, and valve safety',
      'Oxygen equipment types: demand valve, non-rebreather mask, pocket mask with O2 inlet',
    ],
    confinedSkills: [
      'Oxygen equipment assembly and pre-use inspection',
      'Administer O2 via non-rebreather mask to a conscious, breathing victim',
      'Administer O2 via pocket mask or demand valve to an unconscious or non-breathing victim',
      'Monitor oxygen administration: flow rate, mask seal, victim condition',
      'Document and hand over O2 treatment to EMS',
      'Cylinder safety: open, close, secure cylinders; recognize low-supply warning',
      'Access DAN emergency hotline and communicate diving injury information',
    ],
    openWaterSkills: [],
  },
];

/** Quick lookup by template ID */
export const COURSE_TEMPLATE_MAP: Record<string, CourseTemplate> =
  Object.fromEntries(COURSE_TEMPLATES.map(t => [t.id, t]));

export const LEVEL_LABELS: Record<CourseLevel, string> = {
  beginner:     'Beginner',
  intermediate: 'Intermediate',
  advanced:     'Advanced',
  professional: 'Professional',
};

export const LEVEL_COLORS: Record<CourseLevel, string> = {
  beginner:     '#34C759',
  intermediate: '#007AFF',
  advanced:     '#FF9500',
  professional: '#315B7C',
};
